### ISSUE TITLE
Extrenal Feathers installation support

### ISSUE THREAD

**Issue by implex** [SamYStudiO/flair-gradle-plugin#1]
Hi!
Plugin is really great! Thank you!
A few suggestions:
1. Checking of air SDK path by mxmlc instead of air-sdk-descriptor.
2. Explicit enumeration of anes.
This two fixes allow to use external Feathers SDK.

**Comment by SamYStudiO** [comment]
Hi,
thanks for the feedback!

Can you explain more about your suggestions
1. do you mean you aren't using AIR SDK? i mean if you're using a pure AIR SDK or a merged one with Flex SDK you'll get an air-sdk-description.xml xml in both case?
2. you want to include ANEs with a file path insteadof a folder path? maybe check [Gradle-dependencies](https://github.com/SamYStudiO/flair-gradle-plugin/wiki/Gradle-dependencies). You can add ANEs in different way and even separatly for each platforms and or variants:

```
dependencies {
  nativeLibrary files( "app/src/myANEFolder/myANEFile.ane" , "app/src/myANEFolder/myOtherANEFile.ane" )
  iosNativeLibrary fileTree( dir: "app/src/myANEFolder", include: "*.ane" )
  [variant]NativeLibrary files( "app/src/myANEFolder/myANEFile.ane" , "app/src/myANEFolder/myOtherANEFile.ane" )
}
```

**Comment by implex** [comment]
Hi!
1. Both Flex SDK and Feathers SDK contains flex-sdk-description, no air-sdk-description. There is no problem to copy air-sdk-description from pure Air SDK folder, but...
2. You are right, I should enumerate anes in dependencies section, sorry.
Thank you!

**Comment by implex** [comment]
I`ve tryed to build my project rigth now with Feathers SDK 3.0beta, official installation with Feathers SDK Manager. Part of my build script:

```
dependencies {
        nativeLibrary files( "app/libs_ane/aqua.ane", "app/libs_ane/flair.PhysicalDensity.ane")
}

compilerOptions "-external-library-path+=$projectDir/app/libs_ane/aqua.ane"
```

So, if I comment line with compilerOptions, build fail, compiler cant find some classes from ane

**Comment by SamYStudiO** [comment]
ANEs from app/libs_ane are automatically include for compilation, usually you should use dependencies block if you want to add ANEs (or others libraries) outside of default library paths (libs_as, libs_swc and libs_ane) or to make available a library only for a specific platform/variant.

Anyway this doesn't explain why you get that compilation error, are you compiling with gradle task or launcher from intellij/FDT? 
Could you as well send me logs from compilation so i can see which arguments are passed to mxmlc.

**Comment by implex** [comment]
There is a little difference between mxmlc included in Air SDK and mxmlc from Flex/Feathers SDK.
Pure Air mxmlc accept dir path with -external-library-path, Flex/Feathers not, only paths to files. I made a batch file and tried it with Air mxmlc and Feathers mxmlc. Below version working in both cases (take a look at 4th line from the end, without it Flex/Feathers mxmlc fail).

```
mxmlc   +configname=air
-debug=true
-source-path+=pathToProject\build\desktop_debug\classes
-source-path+=pathToProject\build\desktop_debug\asLibraries
-library-path+=pathToProject\build\desktop_debug\libraries
-external-library-path+=pathToProject\build\desktop_debug\extensions
-define+=PLATFORM::ANDROID,false
-define+=PLATFORM::DESKTOP,true
-define+=PRODUCT_FLAVOR::ARMV7,false
-define+=PRODUCT_FLAVOR::X86,false
-define+=BUILD_TYPE::DEBUG,true
-define+=BUILD_TYPE::RELEASE,false
-external-library-path+=pathToProject/app/libs_ane/aqua.ane
-output
pathToProject\build\desktop_debug\package\desktop_debug.swf
pathToProject\build\desktop_debug\classes\com\implex\station\MainDesktop.as
```

**Comment by SamYStudiO** [comment]
Ok thanks for report, i must admit i'm not used to work with pure flex projects, i'll have a look to make plugin compatible with pure flex SDK.

**Comment by implex** [comment]
Thank you!

**Comment by SamYStudiO** [comment]
I've been looking to make the changes but i can't figure out how you generate your desktop build (from your mxmlc logs it looks like you're doing a Desktop build cf. -define+=PLATFORM::DESKTOP,true), how can you get rid of AIR SDK? or are you trying to make a web project? but with web projects you can't use ANE so there is something i can't understand here :)
