### ISSUE TITLE
AIR SDK home issue

### ISSUE THREAD

**Issue by varadig** [SamYStudiO/flair-gradle-plugin#3]
I add (I think a valid) AIR SDK path to local.properties file

`sdk.dir=/Volumes/Work/develop/as3/_SDK_/osx/air27flex4160`

But when I refresh the gradpe project I got this:
`Error:Cannot find AIR SDK home, set a valid AIR SDK home from your local.properties file under project root`

**Comment by SamYStudiO** [comment]
When you open path with finder does it work?

With PC i used double back slash for path instead, could you try on Mac
 `sdk.dir=\\Volumes\\Work\\develop\\as3\\_SDK_\\osx\\air27flex4160`

Finnaly could you check `air-sdk-description.xml` file exists from your SDK (this is the file i'm looking for to validate SDK)

**Comment by varadig** [comment]
The 
`sdk.dir=\\Volumes\\Work\\develop\\as3\\_SDK_\\osx\\air27flex4160`
is not help, but there was no `air-sdk-description.xml` in the sdk folder, just `flex-sdk-description.xml`. Renamed to `air-sdk-description.xml` and works like a charm!

thanks
